language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt > /dev/null

script:
  - python -m unittest -v tests/test.py
