language: python

matrix:
  include:
  - python: 3.5
  - python: 3.6
    dist: xenial
    sudo: true

install:
- pip install -r requirements.txt > /dev/null
- pip install nose coverage
- pip install coveralls

script:
- coverage run --source cookiecutter setup.py test
#- python -m unittest -v tests/test.py

after_sucess:
  coveralls
